# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: rclone

patchesStrategicMerge:
- patch_env.yaml


configMapGenerator:
- name: rclone
  literals:
  - RCLONE_STATS=5s

resources:
- deployment.yaml
- service.yaml