apiVersion: v1
kind: Service
metadata:
  name: rclone-svc
  labels:
    app: rclone
spec:
  ports:
  - name: http-metrics
    port: 80
    protocol: TCP
    targetPort: 5572
  selector:
    app: rclone